name: Lint and Svelte Check

on: [pull_request]

jobs:
 lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | bash -
          echo "$HOME/.pnpm" >> $GITHUB_PATH

      - name: Install dependencies
        run: pnpm install

      - name: Run pnpm lint
        run: pnpm lint

      - name: Run Svelte check
        run: pnpm svelte-check
