name: Lint and Svelte Check

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install pnpm
      run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
    - run: pnpm ci
    - run: pnpm run build --if-present
    - name: Run pnpm lint
      run: pnpm lint
    - name: Run Svelte check
      run: pnpm svelte-check