-- Drop Tables
DROP TABLE IF EXISTS pet_treatments CASCADE;
DROP TABLE IF EXISTS pet_medical_issue CASCADE;
DROP TABLE IF EXISTS medical_issue CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS invoice CASCADE;
DROP TABLE IF EXISTS treatment CASCADE;
DROP TABLE IF EXISTS pet_treatment CASCADE;
DROP TABLE IF EXISTS appointment CASCADE;
DROP TABLE IF EXISTS appointment_status CASCADE;
DROP TABLE IF EXISTS pet CASCADE;
DROP TABLE IF EXISTS customer CASCADE;