name: Node.js CI

on:
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]
          
jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
    - name: install dependencies
      run: pnpm ci
      working-directory: ./physio_praxis_svelte
    - run: pnpm run build --if-present
      working-directory: ./physio_praxis_svelte
    - name: Run pnpm lint
      run: pnpm lint
      working-directory: ./physio_praxis_svelte
    - name: Run Svelte check
      run: pnpm svelte-check
      working-directory: ./physio_praxis_svelte
