name: Node.js CI

on:
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]
          
jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
    - name: action script
      run: |
        cd ./physio_praxis_svelte
        pnpm ci
        pnpm run build --if-present
        pnpm lint
        pnpm svelte-check
